/**
 * The manifest's icons have to be the sizes it claims they are.
 *
 * Chrome does not complain about a 48×48 file declared as the 128 — it scales it
 * and the toolbar quietly looks soft. These are generated by
 * `npm run build:mark` and committed, so this checks the committed bytes rather
 * than the generator.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(readFileSync(resolve(root, 'public/manifest.json'), 'utf8')) as {
  icons: Record<string, string>;
};

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

const entries = Object.entries(manifest.icons);

describe('the extension icons', () => {
  it('declares the four sizes Chrome asks for', () => {
    expect(entries.map(([size]) => size)).toEqual(['16', '32', '48', '128']);
  });

  it.each(entries)('%s is a square PNG of that size', (size, path) => {
    const file = readFileSync(resolve(root, 'public', path));

    expect(file.subarray(0, 8)).toEqual(PNG_SIGNATURE);

    // IHDR is the first chunk: 8 bytes of signature, 4 of length, 4 of type,
    // then width and height as big-endian 32-bit integers.
    expect(file.readUInt32BE(16)).toBe(Number(size));
    expect(file.readUInt32BE(20)).toBe(Number(size));
  });

  it('is drawn with an alpha channel, so it sits on any toolbar', () => {
    for (const [, path] of entries) {
      // Byte 25 is the IHDR colour type. 6 is RGBA.
      expect(readFileSync(resolve(root, 'public', path))[25]).toBe(6);
    }
  });
});
