/**
 * Lucide icon geometry.
 *
 * GENERATED by scripts/build-icons.mjs from lucide-static 1.31.0 (ISC).
 * Do not edit: add the name to ICONS in that script and run `npm run build:icons`.
 *
 * Only the drawing is kept — size, stroke and colour come from the .icon rule in
 * src/ui/styles/base.css, so every icon inherits the text around it.
 */

export const ICON_PATHS = {
  /** start recording; empty flow state */
  'circle-dot':
    '<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="1"/>',
  /** stop recording */
  'square':
    '<rect width="18" height="18" x="3" y="3" rx="2"/>',
  /** pause recording */
  'pause':
    '<rect x="14" y="3" width="5" height="18" rx="1"/><rect x="5" y="3" width="5" height="18" rx="1"/>',
  /** resume recording */
  'play':
    '<path d="M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z"/>',
  /** open the settings page */
  'settings':
    '<path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"/><circle cx="12" cy="12" r="3"/>',
  /** discard a flow */
  'trash-2':
    '<path d="M10 11v6"/><path d="M14 11v6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M3 6h18"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>',
  /** open a flow */
  'chevron-right':
    '<path d="m9 18 6-6-6-6"/>',
  /** expand a disclosure */
  'chevron-down':
    '<path d="m6 9 6 6 6-6"/>',
  /** leave for another surface */
  'arrow-up-right':
    '<path d="M7 7h10v10"/><path d="M7 17 17 7"/>',
  /** reload the tab before recording */
  'refresh-cw':
    '<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/><path d="M21 3v5h-5"/><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/><path d="M8 16H3v5"/>',
  /** blocked tab; approaching a limit */
  'triangle-alert':
    '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/><path d="M12 9v4"/><path d="M12 17h.01"/>',
  /** success toast */
  'circle-check':
    '<circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/>',
  /** failure toast */
  'circle-x':
    '<circle cx="12" cy="12" r="10"/><path d="m15 9-6 6"/><path d="m9 9 6 6"/>',
  /** informational banner */
  'info':
    '<circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/>',
  /** dismiss */
  'x':
    '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
  /** the flow library */
  'folder-open':
    '<path d="m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2"/>',
  /** storage usage */
  'hard-drive':
    '<path d="M10 16h.01"/><path d="M2.212 11.577a2 2 0 0 0-.212.896V18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5.527a2 2 0 0 0-.212-.896L18.55 5.11A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/><path d="M21.946 12.013H2.054"/><path d="M6 16h.01"/>',
  /** work in progress */
  'loader-circle':
    '<path d="M21 12a9 9 0 1 1-6.219-8.56"/>',
} as const;

export type IconName = keyof typeof ICON_PATHS;
