/**
 * Generates src/ui/icons.generated.ts from lucide-static icon definitions.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const iconDir = resolve(root, 'node_modules/lucide-static/icons');
const outFile = resolve(root, 'src/ui/icons.generated.ts');

/** Lucide icon mapping used across extension surfaces. */
const ICONS = {
  'circle-dot': 'start recording; empty flow state',
  square: 'stop recording',
  pause: 'pause recording',
  play: 'resume recording',
  settings: 'open the settings page',
  'trash-2': 'discard a flow',
  'chevron-right': 'open a flow',
  'chevron-down': 'expand a disclosure',
  'arrow-up-right': 'leave for another surface',
  'refresh-cw': 'reload the tab before recording',
  'triangle-alert': 'blocked tab; approaching a limit',
  'circle-check': 'success toast',
  'circle-x': 'failure toast',
  info: 'informational banner',
  x: 'dismiss',
  'folder-open': 'the flow library',
  'hard-drive': 'storage usage',
  'loader-circle': 'work in progress',

  // Viewer chrome
  'arrow-left': 'back to the library',
  search: 'filter the library',
  download: 'export a flow',
  pencil: 'rename a flow',
  sparkles: 'send a flow to Claude',
  ellipsis: 'the overflow menu',
  copy: 'copy a selector or URL',
  'folder-plus': 'save the current recording to the library',
  'circle-help': 'the keyboard shortcut sheet',

  // Step types
  globe: 'a navigate step',
  'mouse-pointer-click': 'a click step',
  keyboard: 'an input step',
  'sticky-note': 'a note step',
  'corner-down-right': 'the page-changed marker',
  atom: 'the React component a step happened in',

  // Screenshots
  image: 'annotate a screenshot',
  'maximize-2': 'open a screenshot full size',
  'image-up': "replace a step's screenshot with a file",
  'image-plus': 'add a screenshot to a step that has none',

  // Export formats
  'file-archive': 'the ZIP export',
  'file-text': 'the Markdown export',
  braces: 'the JSON export',

  // Annotation editor
  'mouse-pointer': 'the select tool',
  'pen-tool': 'the freehand pen tool',
  circle: 'the ellipse tool',
  highlighter: 'the highlight tool',
  type: 'the text tool',
  'eye-off': 'the redact tool — pixelates a region',
  'undo-2': 'undo an annotation',
  'redo-2': 'redo an annotation',
  minus: 'zoom out',
  plus: 'zoom in',

  // Settings
  'rotate-ccw': 'reset a setting to its default',
  'search-x': 'a search that matched no setting',
  upload: 'import a settings file',
  check: 'a selected option in a multi-select',
};

/** Extracts inner SVG path geometry from an icon file. */
function extractBody(name) {
  const svg = readFileSync(resolve(iconDir, `${name}.svg`), 'utf8');
  const inner = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'));

  return inner
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .join('')
    .replace(/\s*\/>/g, '/>')
    .replace(/>\s+</g, '><');
}

const version = JSON.parse(
  readFileSync(resolve(root, 'node_modules/lucide-static/package.json'), 'utf8'),
).version;

const entries = Object.entries(ICONS)
  .map(([name, use]) => `  /** ${use} */\n  '${name}':\n    '${extractBody(name)}',`)
  .join('\n');

const source = `/**
 * Lucide icon geometry.
 *
 * GENERATED by scripts/build-icons.mjs from lucide-static ${version} (ISC).
 * Do not edit directly: add icons to ICONS in scripts/build-icons.mjs.
 */

export const ICON_PATHS = {
${entries}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;

writeFileSync(outFile, source);
console.log(`icons: wrote ${Object.keys(ICONS).length} to ${outFile}`);
